apiVersion: v1
kind: Service
metadata:
  labels:
    app: tylerboydca
  name: tylerboydca-service
  namespace: default
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 3000
  selector:
    app: tylerboydca
  sessionAffinity: None
  type: NodePort
